"""
GigMoney Guru - Financial Context (Shared State for Agent Graph)

This is the central state object that flows through all agents in the LangGraph.
Each agent reads from and writes to this context.
"""
from typing import Optional, List, Dict, Any, TypedDict
from datetime import datetime, date
from pydantic import BaseModel, Field


class IncomePattern(BaseModel):
    """Income patterns detected by Income Pattern Agent."""
    weekday_average: float = 0
    weekend_average: float = 0
    weekly_average: float = 0
    monthly_average: float = 0
    
    # Trends
    trend_direction: str = "flat"  # "up", "down", "flat"
    trend_percentage: float = 0
    
    # By platform
    platform_breakdown: Dict[str, float] = {}
    
    # Seasonality (mocked)
    season_tag: Optional[str] = None  # "monsoon", "festive", "normal"
    season_multiplier: float = 1.0


class ObligationRisk(BaseModel):
    """Risk assessment for an obligation."""
    obligation_id: str
    obligation_name: str
    category: str
    amount: float
    due_date: date
    days_until_due: int
    
    # Risk
    risk_level: str  # "low", "medium", "high"
    risk_score: float  # 0-100
    
    # Projection
    projected_bucket_balance: float
    shortfall_amount: float = 0
    
    # Flags
    is_red_flag: bool = False


class DayForecast(BaseModel):
    """Single day forecast."""
    date: date
    day_of_week: int  # 0=Monday, 6=Sunday
    is_weekend: bool
    
    start_balance: float
    projected_income: float
    projected_expenses: float
    obligations_due: float
    end_balance: float
    
    status: str  # "safe", "tight", "shortfall"


class BucketAllocation(BaseModel):
    """Allocation to a single bucket."""
    bucket_name: str
    amount: float
    reason: str


class TodayAllocation(BaseModel):
    """Today's allocation plan."""
    date: date
    total_income: float
    allocations: List[BucketAllocation]
    safe_to_spend: float
    adjustments_made: List[str] = []


class AdvanceProposal(BaseModel):
    """Proposed micro-advance."""
    needed: bool = False
    principal: float = 0
    purpose: str = ""
    obligation_name: Optional[str] = None
    repayment_date: Optional[date] = None
    repayment_source: str = "weekend_earnings"
    max_percentage: float = 40
    risk_score: str = "low"
    risk_explanation: str = ""
    impact_explanation: str = ""
    without_advance_scenario: str = ""
    weekly_income_estimate: float = 0
    advance_to_income_ratio: float = 0


class GoalScenarioResult(BaseModel):
    """Result of goal scenario analysis."""
    goal_id: str
    goal_name: str
    current_progress: float
    projected_completion_date: Optional[date] = None
    
    # Scenario
    scenario_applied: Optional[str] = None
    scenario_completion_date: Optional[date] = None
    days_difference: int = 0


class ConversationMessage(BaseModel):
    """Message generated by Conversation Agent."""
    content: str
    message_type: str = "text"
    quick_replies: List[Dict[str, Any]] = []
    priority: int = 5  # 1-10, for ordering


class Explanation(BaseModel):
    """Explanation generated by Explainability Agent."""
    topic: str
    explanation: str
    data_points: Dict[str, Any] = {}


class FinancialContext(BaseModel):
    """
    The complete financial context that flows through all agents.
    This is the shared state for the LangGraph.
    """
    # Identity
    user_id: str
    run_id: str
    run_date: date
    
    # User profile
    user_name: str = ""
    preferred_language: str = "hinglish"
    
    # Current balances
    total_balance: float = 0
    bucket_balances: Dict[str, float] = {}
    
    # Today's income
    today_income: float = 0
    today_income_events: List[Dict[str, Any]] = []
    
    # Recent history (for pattern detection)
    income_history: List[Dict[str, Any]] = []  # Last 30 days
    expense_history: List[Dict[str, Any]] = []
    
    # Obligations
    obligations: List[Dict[str, Any]] = []
    
    # Goals
    goals: List[Dict[str, Any]] = []
    
    # Active advances
    active_advances: List[Dict[str, Any]] = []
    
    # ===== AGENT OUTPUTS =====
    
    # From Income Pattern Agent
    income_patterns: Optional[IncomePattern] = None
    
    # From Obligation Risk Agent
    obligation_risks: List[ObligationRisk] = []
    red_flag_days: List[date] = []
    
    # From Cashflow Planner Agent
    forecast: List[DayForecast] = []
    forecast_summary: str = ""
    
    # From Bucket Allocation Agent
    today_allocation: Optional[TodayAllocation] = None
    
    # From Micro-Advance Agent
    advance_proposal: Optional[AdvanceProposal] = None
    
    # From Goal & Scenario Agent
    goal_scenarios: List[GoalScenarioResult] = []
    
    # From Conversation Agent
    messages: List[ConversationMessage] = []
    
    # From Explainability Agent
    explanations: List[Explanation] = []
    
    # Warnings and flags
    warnings: List[str] = []
    has_shortfall: bool = False
    needs_advance: bool = False
    
    class Config:
        arbitrary_types_allowed = True


# TypedDict version for LangGraph compatibility
class FinancialContextDict(TypedDict, total=False):
    """TypedDict version for LangGraph state."""
    user_id: str
    run_id: str
    run_date: str  # ISO format
    user_name: str
    preferred_language: str
    total_balance: float
    bucket_balances: Dict[str, float]
    today_income: float
    today_income_events: List[Dict[str, Any]]
    income_history: List[Dict[str, Any]]
    expense_history: List[Dict[str, Any]]
    obligations: List[Dict[str, Any]]
    goals: List[Dict[str, Any]]
    active_advances: List[Dict[str, Any]]
    income_patterns: Dict[str, Any]
    obligation_risks: List[Dict[str, Any]]
    red_flag_days: List[str]
    forecast: List[Dict[str, Any]]
    forecast_summary: str
    today_allocation: Dict[str, Any]
    advance_proposal: Dict[str, Any]
    goal_scenarios: List[Dict[str, Any]]
    messages: List[Dict[str, Any]]
    explanations: List[Dict[str, Any]]
    warnings: List[str]
    has_shortfall: bool
    needs_advance: bool
